#' Automatically generate a package help menu
#'
#' Based on .Rd files found in the /man/ folder of the package source,
#' this function will generate a file <package>.R with roxygen notation that
#' links to all files found in the /man/ folder. The effect is that package users
#' will get a menu to all help documentation in the package by typing ?<package> \cr
#' This function is not exported because it is not supposed to be run by package users,
#' only by package developers. Call it with <package>:::generate_package_help_menu_roxygen()
#'
#' @param man_dir The path to the /man/ directory where .Rd files can be listed.
#' Default assumes the current working directory is the root of the package
#' source, and specifies the /man/ subdirectory.
#' @param R_dir The path to the /R/ directory where <package>.R can be saved. Default
#' assumes the current working directory is the root of the package source,
#' and specifies the /R/ subdirectory.
#'
#' @examples
#'
#' # start by opening the package project
#' generate_package_help_menu_roxygen()
#' # then do ctrl+shift+B or re-install the package some other way


generate_package_help_menu_roxygen <- function(package_name, man_dir = "man", R_dir = "R") {
    if ( missing(package_name) ) {
        message("Error: Provide the name of the current package as a string.")
        return(FALSE)
    }
  devtools::document()
  helpfiles <- list.files(man_dir)
  helpfiles <- gsub("\\.Rd$", "", helpfiles)
  helpfiles <- paste0("#' \\code{\\link{", helpfiles, "}}\\cr")
  header <- c(paste0("#' ", package_name, " package help menu"),
              "#'",
              "#' This help file is automatically generated by running",
              "#' \\code{\\link{generate_package_help_menu_roxygen}}",
              "#' (The function is defined in R/generate_package_help_menu_roxygen.R)",
              "#'")
  footer <- c("#'",
              "#' @docType package",
              paste0("#' @name ", package_name),
              "#' @encoding UTF-8",
              "NULL")
  package_R <- data.frame(file = c(header, helpfiles, footer), stringsAsFactors = F)
  write.table(package_R,
              file = paste0("R/", package_name, ".R"),
              append = F,
              quote = F,
              sep = "",
              eol = "\n",
              row.names = F,
              col.names = F)
  devtools::document()
  message(paste(package_name, "package help menu upated") )
  return(TRUE)
}

