#' sftp package help menu
#' 
#' This help menu is automatically generated by running
#' \code{make_help_menu}
#' (The function is defined in R/make_help_menu.R)
#'
#' \code{\link{sftp_changedir}}\cr
#' \code{\link{sftp_connect}}\cr
#' \code{\link{sftp_delete}}\cr
#' \code{\link{sftp_download}}\cr
#' \code{\link{sftp_list}}\cr
#' \code{\link{sftp_listdirs}}\cr
#' \code{\link{sftp_listfiles}}\cr
#' \code{\link{sftp_makedir}}\cr
#' \code{\link{sftp_removedir}}\cr
#' \code{\link{sftp_rename}}\cr
#' \code{\link{sftp_upload}}\cr
#'
#' @docType package
#' @name sftp
#' @encoding UTF-8
#' @export
sftp <- function() {?sftp}
